version: "3.8"
services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: broker_mqtt
        restart: always
        networks:
            stack-network:
                ipv4_address: 172.20.0.10
        volumes:
            - ./docker_configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./volumes/mosquitto:/mosquitto
        ports:
            - 1883:1883
            - 9001:9001
    socketi:
        image: quay.io/soketi/soketi:1.4-16-debian
        container_name: socketi
        restart: always
        ports:
            - 6001:6001
            - 9601:9601
        networks:
            stack-network:
                ipv4_address: 172.20.0.2
        environment:
            - SOKETI_DEFAULT_APP_ID=laravelApp
            - SOKETI_DEFAULT_APP_KEY=appkey
            - SOKETI_DEFAULT_APP_SECRET=app-secret
            - SOKETI_DEBUG=1

    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./volumes/redis:/data
        networks:
            stack-network:
                ipv4_address: 172.20.0.4

    chirpstack:
        image: chirpstack/chirpstack:4
        command: -c /etc/chirpstack
        restart: unless-stopped
        volumes:
            - ./docker_configuration/chirpstack:/etc/chirpstack
            - ./lorawan-devices:/opt/lorawan-devices
        depends_on:
            - postgres
            - mosquitto
            - redis
        networks:
            stack-network:
                ipv4_address: 172.20.0.5
        environment:
            - MQTT_BROKER_HOST=172.20.0.10
            - REDIS_HOST=172.20.0.4
            - POSTGRESQL_HOST=172.20.0.9
        ports:
            - 8081:8081
        expose:
            - 8081:tcp

    chirpstack-gateway-bridge:
        image: chirpstack/chirpstack-gateway-bridge:4
        restart: unless-stopped
        ports:
            - 1700:1700/udp
        networks:
            stack-network:
                ipv4_address: 172.20.0.6
        volumes:
            - ./docker_configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
        environment:
            - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
            - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
            - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
            - MQTT_BROKER_HOST=172.20.0.10
        depends_on:
            - mosquitto

    chirpstack-gateway-bridge-basicstation:
        image: chirpstack/chirpstack-gateway-bridge:4
        restart: unless-stopped
        command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
        ports:
            - 3001:3001
        volumes:
            - ./docker_configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
        depends_on:
            - mosquitto
        networks:
            stack-network:
                ipv4_address: 172.20.0.7


    chirpstack-rest-api:
        image: chirpstack/chirpstack-rest-api:4
        restart: unless-stopped
        command: --server chirpstack:8081 --bind 0.0.0.0:8090 --insecure
        ports:
            - 8090:8090
        depends_on:
            - chirpstack
        networks:
            stack-network:
                ipv4_address: 172.20.0.8

    postgres:
        image: postgres:14-alpine
        restart: unless-stopped
        volumes:
            - ./docker_configuration/postgresql/initdb:/docker-entrypoint-initdb.d
            - ./volumes/postgresql:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=root
        networks:
            stack-network:
                ipv4_address: 172.20.0.9



networks:
    stack-network:
        ipam:
            config:
                -   subnet: 172.20.0.0/24
                    gateway : 172.20.0.254

        driver: bridge
