http:
  routers:
    api:
      rule: Host(`traefik.co2.co`)
      service: api@internal
      entryPoints:
        - "http"
        - "https"
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
          - "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"
